[package]
name = "xitca-postgres-toasty"
version = "0.1.0"
edition = "2024"

[dependencies]
xitca-postgres = { version = "0.3", features = ["compat"] }

anyhow = "1"
futures-core = { version = "0.3.31", default-features = false }
pin-project-lite = "0.2.16"
postgres-types = "0.2"
toasty-core = "0.1.0"
toasty-sql = "0.1"
tokio = { version = "1", default-features = false }

[dev-dependencies]
toasty = "0.1"
tokio = { version = "1", features = ["rt", "macros"] }

[patch.crates-io]
xitca-postgres = { git = "http://github.com/HFQR/xitca-web", rev = "c9c4b25" }

toasty = { git = "http://github.com/tokio-rs/toasty", rev = "e0c84c5" }
toasty-core = { git = "http://github.com/tokio-rs/toasty", rev = "e0c84c5" }
toasty-sql = { git = "http://github.com/tokio-rs/toasty", rev = "e0c84c5" }
